language: python
python:
- '3.7'
branches:
  only:
  - staging
before_script:
- pip install -r requirements.txt
env: DJANGO_SETTINGS_MODULE="pureBeurreOC.settings.travis"
services:
- postgresql
script:
- python manage.py test
before_install:
  - sudo apt-get update
  - sudo apt-get install firefox
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver