language: python
python:
- '3.7'
branches:
  only:
  - master
before_script:
- pip install -r requirements.txt
env: DJANGO_SETTINGS_MODULE="pureBeurreOC.settings.travis"
services:
- postgresql
script:
- python manage.py test
after_script:
  - ssh -i ./deploy_key erwan@161.35.159.197 cd /home/erwan/purBeurre && git pull origin master
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in ./deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host {SERVER_IP}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key