language: python
python:
  - '3.7'

# safelist
branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pureBeurreOC.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
